# -*- coding: utf-8 -*-
"""Python_Assignment2.pynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ie_X4o5R7P__-d5w-IWddQFK92rdwa8-

1.WAP to determine a student’s
final grade and indicate whether
they are passing or failing. The
final grade is calculated as the
average of marks of four
subjects.
"""

m1=float(input(print("Enter marks of subject 1:")))
m2=float(input(print("Enter marks of subject 2:")))
m3=float(input(print("Enter marks of subject 3:")))
m4=float(input(print("Enter marks of subject 4:")))
avg=(m1+m2+m3+m4)//4
print(avg)
print("Your Grade:",avg)
if avg<40:
  print("Sorry you failed")
else:
  print("Congratulations you have passed")

"""2.WAP to find the largest number
between two inputted numbers
"""

n1=input(print("Enter 1st number:"))
n2=input(print("Enter 2nd number:"))
if(n1>n2):
  print("1st number is greater")
else:
  print("2nd number is greater")

"""3.WAP that reads two numbers
and an arithmetic operator and
displays the result.
"""

i1=float(input(print("Enter 1st number:")))
i2=float(input(print("Enter 2nd number:")))
op=input("Enter operator")
if op=='*':
  print("Result:",i1*i2)
if op=='/':
  print("Result:",i1/i2)
if op=='+':
  print("Result:",i1+i2)
if op=='-':
  print("Result:",i1-i2)

"""4.Write a program to accept a
character from the user and
display whether it is a vowel or
consonant.
"""

var=input("Enter a character")
if var=='a' or var=='e' or var=='i' or var=='o' or var=='u' or var=='A' or var=='E' or var=='I' or var=='O' or var=='U':
  print(var,"is a vowel")
else:
  print(var, "is a consonant")

"""6.WAP to input a number and
check whether the number is
divisible by 5 and 3 or not
"""

num=int(input("Enter a no "))
if num%5==0 and num%3==0:
  print("The number is divisible")
else:
  print("The number is not divisible")

"""7.WAP to input 3 numbers and
find the second smallest.

"""

print("Enter 3 numbers")
x, y, z = int(input()), int(input()), int(input())
if x<y<z or z<y<x:
   print(y,"is the second smallest number")
elif y<z<x or x<z<y:
    print(z,"is the second smallest number")
else:
    print(x,"is the second smallest number")

"""8. WAP to input marks of 5
subject and find average and
assign grade.
Average Marks Grade
90 & above O
80 – 89 E
70-79 A
Below 70 B
Enter the marks of five
subjects: 50 30 45 50 48
Grade is B
"""

avg=0.0
print("Enter marks of 5 subjects:")
m1,m2,m3,m4,m5=float(input()),int(input()),int(input()),int(input()),int(input())
avg=(m1+m2+m3+m4+m5)//5
if avg>=90:
  print("Grade is O")
elif avg>=80 and avg<=89:
  print("Grade is E")
elif avg>=70 and avg<=79:
  print("Grade is A")
elif avg<70:
  print("Grade is B")

"""9. WAP to input consumed unit
and calculate Electricity Bill,
where monthly rent Rs. 300.
Unit Charge per unit(Rs.)
Upto 300 7
301- 800 9
801-1500 12
1501 & above 15

Enter your consumed unit: 450
Your total bill is: 3450
[300*7+(450-300)*9=3450]

Enter your consumed unit:
10
Your total bill is: 300
[10*7=70. But Monthly rent
Rs. 300 Consumer has to pay
minimum Rs 300]

"""

bill=0
var=float(input("Enter your consumed unit "))
if var<=300:
  bill+=300
elif var>=301 and var<=800:
  bill+=(300*7)+(var-300)*9
elif var>=801 and var<=1500:
  bill+=(300*7)+((801-300)*9)+((var-800)*12)
else :
  bill+=(300*7)+((801-300)*9)+((1500-801)*12)+((var-1500)*15)
print("Your total bill is:",bill)

"""10.WAP to input 3 side of a
triangle and prints its type (i.e
Equilateral/Isosceles/Scalene).
"""

print("Enter the length of 3 sides of the triangle")
l1,l2,l3=float(input()),float(input()),float(input())
if l1==l2==l3:
  print("Equilateral")
elif l1==l2 or l1==l3 or l2==l3:
   print("Isosceles")
else:
  print("Scalene")